export type NetlifyReadyState = string;

export type NetlifyUser = {
  email: string;
  affiliate_id: string;
  avatar: string;
  avatar_url: string;
  connected_accounts: { github: string };
  created_at: string;
  full_name: string;
  has_pending_email_verification: boolean;
  id: string;
  last_login: string;
  login_providers: string[];
  mfa_enabled: boolean;
  onboarding_progress: { overview: string };
  pending_email?: string;
  preferred_account_id: string;
  saml_account_id: string;
  saml_slug?: string;
  sandbox: boolean;
  site_count: number;
  slug: string;
  tracking_id: string;
  uid?: string;
};

export type NetlifyDeployment = {
  id: string;
  site_id: string;
  user_id: string;
  build_id: string;
  state: string;
  name: string;
  url: string;
  ssl_url: string;
  admin_url: string;
  deploy_url: string;
  deploy_ssl_url: string;
  screenshot_url: string;
  review_id: 0;
  draft: boolean;
  required: string[];
  required_functions: string[];
  error_message: string;
  branch: string;
  commit_ref: string;
  commit_url: string;
  skipped: boolean;
  created_at: string;
  updated_at: string;
  published_at: string;
  title: string;
  context: string;
  locked: boolean;
  review_url: string;
  site_capabilities: {
    large_media_enabled: boolean;
  };
  framework: string;
};

export type NetlifyBuild = {
  branch: string;
  build_time: number;
  commit_ref: string;
  commit_url: string;
  committer: string;
  context: string;
  admin_url: string;
  created_at: string;
  custom_domain: string;
  deploy_id: string;
  deploy_ssl_url: string;
  deploy_state: string;
  deploy_time: number;
  done: boolean;
  error?: any;
  error_message?: string;
  id: string;
  links: {
    alias: string;
    branch: null;
    permalink: string;
  };
  priority: any;
  review_id: number;
  review_url: string;
  sha: string;
  site_id: string;
  started_at: string;
  subdomain: string;
  title: string;
  state: NetlifyReadyState;
};
