name: Build Release

on:
  push:
    branches:
      - main

jobs:
  build_release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@master
        with:
          ref: main
      - name: Add MacOS Certificates
        if: runner.os == 'macOS'
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATE_MACOS_APP }}
          p12-password: ${{ secrets.CERTIFICATE_MACOS_PASS }}
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Build
        if: runner.os == 'macOS'
        run: yarn make --arch x64,arm64
      - name: Build on Windows
        if: runner.os == 'Windows'
        run: yarn make --arch x64
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: |
            out/make/zip/darwin/**/*.zip
            out/**/*.exe
          prerelease: false
          automatic_release_tag: 'latest'
          title: 'Main Build'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
