name: Build

on:
  push:
    branches:
      - main

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: main
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Build on MacOS
        run: yarn make --arch x64,arm64
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: |
            out/make/zip/darwin/**/*.zip
            out/**/*.app
          prerelease: false
          automatic_release_tag: 'latest'
          title: 'Main Build'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
