name: Build

on:
  push:
    branches:
      - main

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: main
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Add MacOS Certificates
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/')
        run: chmod +x ./scripts/add-osx-cert.sh && ./scripts/add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      - name: Install dependencies
        run: yarn install
      - name: Build on MacOS
        run: yarn make --arch x64,arm64
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: |
            out/make/zip/darwin/**/*.zip
          prerelease: false
          automatic_release_tag: 'latest'
          title: 'Main Build'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
